# Generated by Django 3.0.8 on 2020-07-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
